---
# https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28
# input vars: gh_repo=owner/repo, gh_release, gh_json_query

- name: Get release information from Github API
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ gh_repo }}/releases/tags/{{ gh_release | default('latest') }}"
    return_content: true
  register: gh_info
  until: gh_info is success
  changed_when: false
  environment: "{{ proxy_env | default(omit) }}"

- name: Set fact
  ansible.builtin.set_fact:
    gh_dl_url: "{{ gh_info.json | community.general.json_query(gh_json_query) | first }}"

- name: Download archive
  ansible.builtin.get_url:
    url: "{{ gh_dl_url }}"
    dest: "{{ install_archives }}/{{ gh_dl_url | basename }}"
    mode: '{{ gh_mode | default("0600") }}'
  environment: "{{ proxy_env | default(omit) }}"

- name: Download checksums
  ansible.builtin.get_url:
    url: "https://github.com/kunai-project/kunai/releases/download/{{ gh_release }}/sha512.txt"
    dest: "{{ install_archives }}/kunai-{{ gh_release }}-sha512.txt"
    mode: '0600'
  environment: "{{ proxy_env | default(omit) }}"

- name: Get archive checksum
  ansible.builtin.stat:
    path: "{{ install_archives }}/{{ gh_dl_url | basename }}"
    get_checksum: true
    checksum_algorithm: sha512
  register: kunai_f

- name: Get expected archive checksum
  ansible.builtin.command:
    cmd: "grep {{ kunai_arch }} {{ install_archives }}/kunai-{{ gh_release }}-sha512.txt"
  changed_when: false
  register: kunai_expected

- name: Validate checksum
  ansible.builtin.assert:
    that:
      - kunai_f.stat.checksum == kunai_expected.stdout | split | first
