---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - not is_container|bool

- name: Restart kunai
  ansible.builtin.service:
    name: 00-kunai
    state: restarted
  when:
    - not is_container|bool

- name: Restart kunailog
  ansible.builtin.service:
    name: kunailog.path
    state: restarted
  when:
    - not is_container|bool

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when:
    - not is_container|bool
