---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - not is_container|bool

- name: Restart kunai
  ansible.builtin.service:
    name: kunai
    state: restarted
  when:
    - not is_container|bool
