---

- name: Verify
  hosts: "{{ playbook_hosts | default('all') }}"
  vars:
    exec_file: /usr/bin/kunai
    processes:
      - { u: root, p: kunai }
    ports: []
    #   - { h: 127.0.0.1, p: 8080 }
    is_container: false
  pre_tasks:
    - name: RedHat | Ensure ps and host are present
      ansible.builtin.package:
        name:
          - procps-ng
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
    - name: Debian | Ensure ps and host present
      ansible.builtin.package:
        name:
          - procps
          # EDR-Telemetry generator
          - python3-dbus
          - python3-libuser
          - git
          - "linux-headers-{{ ansible_kernel }}"
        state: present
      when: ansible_os_family == "Debian"
    - name: Ensure prettytable pip is present
      ansible.builtin.pip:
        name: prettytable
        state: present
    - name: Debug | var ansible_virtualization_type
      ansible.builtin.debug:
        var: ansible_virtualization_type
    - name: Set fact is_container
      ansible.builtin.set_fact:
        is_container: true
      when: >
        (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker"
           or ansible_virtualization_type == "containerd"
           or ansible_virtualization_type == "container"
          )
        )
  tasks:
    - name: Check executable
      ansible.builtin.stat:
        path: "{{ exec_file }}"
      register: bin1
      become: yes
    - name: Validate executable is present
      ansible.builtin.assert:
        that:
          - bin1.stat.exists and bin1.stat.size != 0 and bin1.stat.mode == '0755'

    - name: Ensure processes are running
      ansible.builtin.command:
        cmd: "pgrep -u {{ item.u }} {{ item.p }}"
      register: ps
      changed_when: false
      failed_when: false
      loop: "{{ processes }}"
    - name: Validate ps output
      ansible.builtin.assert:
        that:
          - item.stdout | length > 0
      loop: "{{ ps.results }}"
      when:
        - not is_container|bool

    - name: Check all processes
      ansible.builtin.command: ps aux
      changed_when: false
      register: psa
    - name: Debug | ps aux output
      ansible.builtin.debug:
        var: psa
        verbosity: 1

    - name: Ensure ports are listening
      ansible.builtin.wait_for:
        host: "{{ item.h }}"
        port: "{{ item.p }}"
        timeout: 10
      with_items: "{{ ports }}"
      when:
        - not is_container|bool

    - name: Get EDR-Telemetry generator
      ansible.builtin.get_url:
        url: https://github.com/tsale/EDR-Telemetry/raw/refs/heads/main/Tools/Telemetry-Generator/Linux/lnx_telem_gen.py
        dest: /tmp/lnx_telem_gen.py
        mode: '0755'

    - name: Run EDR-Telemetry generator
      ansible.builtin.command:  # noqa no-changed-when
        cmd: python3 lnx_telem_gen.py
      args:
        chdir: /tmp
